/*
 * Generated File : Packet_PlayerEntity.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

using CT.Common.DataType;
using CT.Common.Serialization;
using CT.Common.Serialization.Type;

namespace CT.Packets
{
	public sealed partial class EntityPlayerState : IPacketSerializable
	{
		public NetEntityId Id = new();
		public NetEntityType Type;
		public NetTransform Transform = new();
	
		public int SerializeSize => Id.SerializeSize + Transform.SerializeSize + 1;
	
		public void Serialize(PacketWriter writer)
		{
			Id.Serialize(writer);
			writer.Put(Type);
			Transform.Serialize(writer);
		}
	
		public void Deserialize(PacketReader reader)
		{
			Id.Deserialize(reader);
			Type = reader.ReadNetEntityType();
			Transform.Deserialize(reader);
		}
	}
}