/*
 * Generated File : Packet_Gameplay.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

using CT.Common.DataType;
using CT.Common.Serialization;
using CT.Common.Serialization.Type;

namespace CT.Packets
{
	public sealed partial class SC_InitialWorldState : PacketBase
	{
		public override PacketType PacketType => PacketType.SC_InitialWorldState;
	
		public NetStringShort MiniGameName;
	
		public override int SerializeSize => MiniGameName.SerializeSize + 2;
	
		public override void Serialize(PacketWriter writer)
		{
			writer.Put(PacketType);
			writer.Put(MiniGameName);
		}
	
		public override void Deserialize(PacketReader reader)
		{
			MiniGameName = reader.ReadNetStringShort();
		}
	}
	
	
}