using System.Text;

namespace CT.CorePatcher
{
	public static class CodeFormat
	{
		public static string NewLine { get; set; } = TextFormat.LF;
		public static string Indent { get; set; } = TextFormat.Indent;

		/// <summary>입력된 문자열에 들여쓰기를 합니다.</summary>
		public static void AddIndent(StringBuilder content, int repeat = 1)
		{
			string ctn = content.ToString();
			for (int i = 0; i < repeat; i++)
			{
				ctn = Indent + ctn.Replace("\n", $"\n{Indent}");
			}
			content.Clear();
			content.Append(ctn);
		}

		/// <summary>입력된 문자열에 들여쓰기를 합니다.</summary>
		public static string AddIndent(string content, int repeat = 1)
		{
			for (int i = 0; i < repeat; i++)
			{
				content = Indent + content.Replace(NewLine, $"{NewLine}{Indent}");
			}

			return content;
		}

		/// <summary>입력된 문자열에 들여쓰기를 합니다.</summary>
		public static void AddIndent(ref string content, int repeat = 1)
		{
			for (int i = 0; i < repeat; i ++)
			{
				content = Indent + content.Replace(NewLine, $"{NewLine}{Indent}");
			}
		}

		/// <summary>불필요한 개행을 없애고 전처리기 들여쓰기를 제거합니다.</summary>
		/// <param name="content"></param>
		/// <param name="startFromNamespace"></param>
		public static void ReformCode(ref string content, bool startFromNamespace)
		{
			StringBuilder sb = new();

			var contents = content.Split(NewLine);
			int startIndex = 0;

			if (startFromNamespace)
			{
				for (int i = 0; i < contents.Length; i ++)
				{
					string line = contents[i];
					if (line.Contains($"namespace"))
					{
						startIndex = i;
						break;
					}
					sb.AppendLine(line);
				}
			}

			for (int i = startIndex; i < contents.Length ; i ++)
			{
				string line = contents[i];
				if (string.IsNullOrWhiteSpace(line))
					continue;

				foreach (char c in line)
				{
					if (c == ' ' || c == '\t')
						continue;

					if (c == '#')
						line = line.TrimStart();

					break;
				}

				sb.Append(line + NewLine);
			}

			content = sb.ToString();
		}

		/// <summary>
		/// {0} Code file name
		/// {1} Content
		/// </summary>
		public static readonly string GeneratorMetadata =
@"/*
 * Generated File : {0}
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

{1}";
	}
}
