/*
 * Generated File : Master_ZTest_InnerObject
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Numerics;
using System.Collections.Generic;
using CT.Common.DataType;
using CT.Common.Serialization;
using CT.Common.Synchronizations;
using CT.Common.Tools.Collections;
using CTS.Instance.Gameplay;
using CTS.Instance.Synchronizations;
using CTS.Instance.SyncObjects;

namespace CTS.Instance.SyncObjects
{
	[Serializable]
	public partial class ZTest_InnerObject : IMasterSynchronizable
	{
		[SyncVar]
		private int _testInt;
		[SyncRpc]
		public partial void Server_Rename(NetStringShort newName);
		private BitmaskByte _dirtyReliable_0 = new();
		public bool IsDirtyReliable
		{
			get
			{
				bool isDirty = false;
				isDirty |= _dirtyReliable_0.AnyTrue();
				return isDirty;
			}
		}
		public bool IsDirtyUnreliable => false;
		private int TestInt
		{
			get => _testInt;
			set
			{
				if (_testInt == value) return;
				_testInt = value;
				_dirtyReliable_0[0] = true;
			}
		}
		public partial void Server_Rename(NetStringShort newName)
		{
			Server_RenameCallstack.Add(newName);
			_dirtyReliable_0[1] = true;
		}
		private List<NetStringShort> Server_RenameCallstack = new(4);
		public void ClearDirtyReliable()
		{
			_dirtyReliable_0.Clear();
			Server_RenameCallstack.Clear();
		}
		public void ClearDirtyUnreliable() { }
		public void SerializeSyncReliable(NetworkPlayer player, IPacketWriter writer)
		{
			_dirtyReliable_0.Serialize(writer);
			if (_dirtyReliable_0[0])
			{
				writer.Put(_testInt);
			}
			if (_dirtyReliable_0[1])
			{
				byte count = (byte)Server_RenameCallstack.Count;
				writer.Put(count);
				for (int i = 0; i < count; i++)
				{
					var arg = Server_RenameCallstack[i];
					arg.Serialize(writer);
				}
			}
		}
		public void SerializeSyncUnreliable(NetworkPlayer player, IPacketWriter writer) { }
		public void SerializeEveryProperty(IPacketWriter writer)
		{
			writer.Put(_testInt);
		}
		public void InitializeProperties()
		{
			_testInt = 0;
		}
		public bool TryDeserializeSyncReliable(NetworkPlayer player, IPacketReader reader) => true;
		public bool TryDeserializeSyncUnreliable(NetworkPlayer player, IPacketReader reader) => true;
		public void IgnoreSyncReliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticReliable(IPacketReader reader) { }
		public void IgnoreSyncUnreliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticUnreliable(IPacketReader reader) { }
	}
}
#pragma warning restore CS0649
