/*
 * Generated File : Master_ZTest_Parent
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Numerics;
using System.Collections.Generic;
using CT.Common.Gameplay;
using CT.Common.Gameplay.Players;
using CT.Common.DataType;
using CT.Common.DataType.Synchronizations;
using CT.Common.Serialization;
using CT.Common.Synchronizations;
using CT.Common.Tools.Collections;
using CTS.Instance.Gameplay;
using CTS.Instance.Synchronizations;
using CTS.Instance.SyncObjects;

namespace CTS.Instance.SyncObjects
{
	[Serializable]
	public partial class ZTest_Parent
	{
		[SyncVar]
		protected int _field_Server_P1;
		[SyncVar]
		protected float _field_Server_P2;
		[SyncVar]
		protected int _space_1;
		[SyncRpc]
		public partial void Server_P1();
		[SyncRpc(SyncType.ReliableTarget)]
		protected partial void Server_p2(NetworkPlayer player, int a, int b);
		[SyncVar(dir: SyncDirection.FromRemote)]
		protected int _field_Client_P1;
		public int Field_Client_P1 => _field_Client_P1;
		protected Action<int>? _onField_Client_P1Changed;
		public event Action<int> OnField_Client_P1Changed
		{
			add => _onField_Client_P1Changed += value;
			remove => _onField_Client_P1Changed -= value;
		}
		[SyncVar(dir: SyncDirection.FromRemote)]
		protected float _field_Client_P2;
		protected Action<float>? _onField_Client_P2Changed;
		public event Action<float> OnField_Client_P2Changed
		{
			add => _onField_Client_P2Changed += value;
			remove => _onField_Client_P2Changed -= value;
		}
		[SyncRpc(dir: SyncDirection.FromRemote)]
		public partial void Client_P1(NetworkPlayer player);
		[SyncRpc(dir: SyncDirection.FromRemote)]
		protected virtual partial void Client_p2(NetworkPlayer player, int a, int b);
		protected BitmaskByte _dirtyReliable_0 = new();
		public override bool IsDirtyReliable
		{
			get
			{
				bool isDirty = false;
				isDirty |= _dirtyReliable_0.AnyTrue();
				return isDirty;
			}
		}
		public override bool IsDirtyUnreliable => false;
		public int Field_Server_P1
		{
			get => _field_Server_P1;
			set
			{
				if (_field_Server_P1 == value) return;
				_field_Server_P1 = value;
				_dirtyReliable_0[0] = true;
			}
		}
		protected float Field_Server_P2
		{
			get => _field_Server_P2;
			set
			{
				if (_field_Server_P2 == value) return;
				_field_Server_P2 = value;
				_dirtyReliable_0[1] = true;
			}
		}
		public int Space_1
		{
			get => _space_1;
			set
			{
				if (_space_1 == value) return;
				_space_1 = value;
				_dirtyReliable_0[2] = true;
			}
		}
		public partial void Server_P1()
		{
			Server_P1CallstackCount++;
			_dirtyReliable_0[3] = true;
		}
		protected byte Server_P1CallstackCount = 0;
		protected partial void Server_p2(NetworkPlayer player, int a, int b)
		{
			Server_p2iiCallstack.Add(player, (a, b));
			_dirtyReliable_0[4] = true;
		}
		protected TargetCallstack<NetworkPlayer, (int a, int b)> Server_p2iiCallstack = new(8);
		public override void ClearDirtyReliable()
		{
			_dirtyReliable_0.Clear();
			Server_P1CallstackCount = 0;
			Server_p2iiCallstack.Clear();
		}
		public override void ClearDirtyUnreliable() { }
		public override void SerializeSyncReliable(NetworkPlayer player, IPacketWriter writer)
		{
			BitmaskByte dirtyReliable_0 = _dirtyReliable_0;
			int dirtyReliable_0_pos = writer.OffsetSize(sizeof(byte));
			if (_dirtyReliable_0[0])
			{
				writer.Put(_field_Server_P1);
			}
			if (_dirtyReliable_0[1])
			{
				writer.Put(_field_Server_P2);
			}
			if (_dirtyReliable_0[2])
			{
				writer.Put(_space_1);
			}
			if (_dirtyReliable_0[3])
			{
				writer.Put((byte)Server_P1CallstackCount);
			}
			if (_dirtyReliable_0[4])
			{
				int Server_p2iiCount = Server_p2iiCallstack.GetCallCount(player);
				if (Server_p2iiCount > 0)
				{
					var Server_p2iicallList = Server_p2iiCallstack.GetCallList(player);
					writer.Put((byte)Server_p2iiCount);
					for (int i = 0; i < Server_p2iiCount; i++)
					{
						var arg = Server_p2iicallList[i];
						writer.Put(arg.a);
						writer.Put(arg.b);
					}
				}
				else
				{
					dirtyReliable_0[4] = false;
				}
			}
			if (dirtyReliable_0.AnyTrue())
			{
				writer.PutTo(dirtyReliable_0, dirtyReliable_0_pos);
			}
			else
			{
				writer.SetSize(dirtyReliable_0_pos);
			}
		}
		public override void SerializeSyncUnreliable(NetworkPlayer player, IPacketWriter writer) { }
		public override void SerializeEveryProperty(IPacketWriter writer)
		{
			writer.Put(_field_Server_P1);
			writer.Put(_field_Server_P2);
			writer.Put(_space_1);
		}
		public override void InitializeMasterProperties()
		{
			_field_Server_P1 = 0;
			_field_Server_P2 = 0;
			_space_1 = 0;
		}
		public override bool TryDeserializeSyncReliable(NetworkPlayer player, IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				if (!reader.TryReadInt32(out _field_Client_P1)) return false;
				_onField_Client_P1Changed?.Invoke(_field_Client_P1);
			}
			if (dirtyReliable_0[1])
			{
				if (!reader.TryReadSingle(out _field_Client_P2)) return false;
				_onField_Client_P2Changed?.Invoke(_field_Client_P2);
			}
			if (dirtyReliable_0[2])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					Client_P1(player);
				}
			}
			if (dirtyReliable_0[3])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					if (!reader.TryReadInt32(out int a)) return false;
					if (!reader.TryReadInt32(out int b)) return false;
					Client_p2(player, a, b);
				}
			}
			return true;
		}
		public override bool TryDeserializeSyncUnreliable(NetworkPlayer player, IPacketReader reader) => true;
		public override void InitializeRemoteProperties()
		{
			_field_Client_P1 = 0;
			_field_Client_P2 = 0;
		}
		public override void IgnoreSyncReliable(IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				reader.Ignore(4);
			}
			if (dirtyReliable_0[1])
			{
				reader.Ignore(4);
			}
			if (dirtyReliable_0[2])
			{
				reader.Ignore(1);
			}
			if (dirtyReliable_0[3])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					reader.Ignore(4);
					reader.Ignore(4);
				}
			}
		}
		public static void IgnoreSyncStaticReliable(IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				reader.Ignore(4);
			}
			if (dirtyReliable_0[1])
			{
				reader.Ignore(4);
			}
			if (dirtyReliable_0[2])
			{
				reader.Ignore(1);
			}
			if (dirtyReliable_0[3])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					reader.Ignore(4);
					reader.Ignore(4);
				}
			}
		}
		public override void IgnoreSyncUnreliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticUnreliable(IPacketReader reader) { }
	}
}
#pragma warning restore CS0649
