/*
 * Generated File : PacketType.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

namespace CT.Packets
{
	public enum PacketType : byte
	{
		None = 0,
		CS_Req_TryEnterGameInstance,
		SC_Ack_TryEnterGameInstance,
		CS_Req_ReadyToSync,
		CS_Sync_RemoteUnreliable,
		CS_Sync_RemoteReliable,
		SC_Sync_MasterLifeCycle,
		SC_Sync_MasterReliable,
		SC_Sync_MasterUnreliable,
	}
}
