/*
 * Generated File : PacketDispatcher.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

using System.Collections.Generic;
using CT.Packets;
using CT.Common.Serialization;
using CTS.Instance.Networks;

namespace CTS.Instance.Packets
{
	public delegate void HandlePacket(PacketBase receivedPacket, UserSession session);
	public delegate void HandlePacketRaw(PacketReader reader, UserSession session);

	public static class PacketDispatcher
	{
		public static Dictionary<PacketType, HandlePacket> _dispatcherTable = new()
		{
			{ PacketType.CS_Req_TryJoinGameInstance, PacketHandler.Handle_CS_Req_TryJoinGameInstance },
			{ PacketType.CS_Req_UserInput_Movement, PacketHandler.Handle_CS_Req_UserInput_Movement },
			{ PacketType.CS_Req_UserInput_Action, PacketHandler.Handle_CS_Req_UserInput_Action },
			
		};

		private static Dictionary<PacketType, HandlePacketRaw> _dispatcherRawTable = new()
		{
			
		};

		private static HashSet<PacketType> _customPacketSet = new()
		{
			
		};

		public static void Dispatch(PacketBase receivedPacket, UserSession session)
		{
			_dispatcherTable[receivedPacket.PacketType](receivedPacket, session);
		}

		public static void DispatchRaw(PacketType packetType, PacketReader reader, UserSession session)
		{
			_dispatcherRawTable[packetType](reader, session);
		}

		public static bool IsCustomPacket(PacketType packetType)
		{
			return _customPacketSet.Contains(packetType);
		}
	}
}