/*
 * Generated File : Remote_TestInnerObject
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Collections.Generic;
using CT.Common.DataType;
using CT.Common.Serialization;
using CT.Common.Serialization.Type;
using CT.Common.Synchronizations;
using CT.Common.Tools.Collections;
using CTC.Networks.Synchronizations;

namespace CTC.Networks.SyncObjects.TestSyncObjects
{
	[Serializable]
	public partial class TestInnerObject : ISynchronizable
	{
		[SyncVar]
		private int _testInt;
		public event Action<int>? OnTestIntChanged;
		[SyncRpc]
		public partial void Server_Rename(NetStringShort newName);
		public bool IsDirtyReliable => false;
		public bool IsDirtyUnreliable => false;
		public void ClearDirtyReliable() { }
		public void ClearDirtyUnreliable() { }
		public void SerializeSyncReliable(PacketWriter writer) { }
		public void SerializeSyncUnreliable(PacketWriter writer) { }
		public void SerializeEveryProperty(PacketWriter writer) { }
		public void DeserializeSyncReliable(PacketReader reader)
		{
			BitmaskByte _dirtyReliable_0 = reader.ReadBitmaskByte();
			if (_dirtyReliable_0[0])
			{
				_testInt = reader.ReadInt32();
				OnTestIntChanged?.Invoke(_testInt);
			}
			if (_dirtyReliable_0[1])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					NetStringShort newName = new();
					newName.Deserialize(reader);
					Server_Rename(newName);
				}
			}
		}
		public void DeserializeSyncUnreliable(PacketReader reader) { }
		public void DeserializeEveryProperty(PacketReader reader)
		{
			_testInt = reader.ReadInt32();
			OnTestIntChanged?.Invoke(_testInt);
		}
	}
}
#pragma warning restore CS0649
