/*
 * Generated File : PacketDispatcher.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

using System.Collections.Generic;
using CT.Common.Serialization;
using CT.Packets;

namespace CTC.Networks.Packets
{
	public delegate void HandlePacket(PacketBase receivedPacket, ServerSession session);

	public static class PacketDispatcher
	{
		public static Dictionary<PacketType, HandlePacket> _dispatcherTable = new()
		{
			{ PacketType.SC_Ack_TryJoinGameInstance, PacketHandler.Handle_SC_Ack_TryJoinGameInstance },
			{ PacketType.SC_OnUserEnter, PacketHandler.Handle_SC_OnUserEnter },
			{ PacketType.SC_OnUserLeave, PacketHandler.Handle_SC_OnUserLeave },
			{ PacketType.SC_InitialData, PacketHandler.Handle_SC_InitialData },
			{ PacketType.SC_SpawnEntities, PacketHandler.Handle_SC_SpawnEntities },
			
		};

		public static void Dispatch(PacketBase receivedPacket, ServerSession session)
		{
			_dispatcherTable[receivedPacket.PacketType](receivedPacket, session);
		}
	}
}