/*
 * Generated File : Master_PlayerCostume
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Numerics;
using System.Collections.Generic;
using CT.Common;
using CT.Common.DataType;
using CT.Common.Exceptions;
using CT.Common.Gameplay;
using CT.Common.Quantization;
using CT.Common.Serialization;
using CT.Common.Synchronizations;
using CT.Common.Tools;
using CT.Common.DataType.Input;
using CT.Common.DataType.Primitives;
using CT.Common.DataType.Synchronizations;
using CT.Common.Gameplay.PlayerCharacterStates;
using CT.Common.Gameplay.Players;
using CT.Common.Tools.CodeGen;
using CT.Common.Tools.Collections;
using CT.Common.Tools.ConsoleHelper;
using CT.Common.Tools.Data;
using CT.Common.Tools.FSM;
using CT.Common.Tools.GetOpt;
using CT.Common.Tools.SharpJson;
using CTS.Instance.Gameplay;
using CTS.Instance.Synchronizations;
using CTS.Instance.SyncObjects;

namespace CTS.Instance.SyncObjects
{
	[Serializable]
	public partial class PlayerCostume : IMasterSynchronizable
	{
		[SyncVar]
		private int _head;
		[SyncVar]
		private int _hair;
		[SyncVar]
		private int _body;
		private BitmaskByte _dirtyReliable_0 = new();
		public bool IsDirtyReliable
		{
			get
			{
				bool isDirty = false;
				isDirty |= _dirtyReliable_0.AnyTrue();
				return isDirty;
			}
		}
		public bool IsDirtyUnreliable => false;
		public int Head
		{
			get => _head;
			set
			{
				if (_head == value) return;
				_head = value;
				_dirtyReliable_0[0] = true;
			}
		}
		public int Hair
		{
			get => _hair;
			set
			{
				if (_hair == value) return;
				_hair = value;
				_dirtyReliable_0[1] = true;
			}
		}
		public int Body
		{
			get => _body;
			set
			{
				if (_body == value) return;
				_body = value;
				_dirtyReliable_0[2] = true;
			}
		}
		public void ClearDirtyReliable()
		{
			_dirtyReliable_0.Clear();
		}
		public void ClearDirtyUnreliable() { }
		public void SerializeSyncReliable(NetworkPlayer player, IPacketWriter writer)
		{
			_dirtyReliable_0.Serialize(writer);
			if (_dirtyReliable_0[0])
			{
				writer.Put(_head);
			}
			if (_dirtyReliable_0[1])
			{
				writer.Put(_hair);
			}
			if (_dirtyReliable_0[2])
			{
				writer.Put(_body);
			}
		}
		public void SerializeSyncUnreliable(NetworkPlayer player, IPacketWriter writer) { }
		public void SerializeEveryProperty(IPacketWriter writer)
		{
			writer.Put(_head);
			writer.Put(_hair);
			writer.Put(_body);
		}
		public void InitializeMasterProperties()
		{
			_head = 0;
			_hair = 0;
			_body = 0;
		}
		public bool TryDeserializeSyncReliable(NetworkPlayer player, IPacketReader reader) => true;
		public bool TryDeserializeSyncUnreliable(NetworkPlayer player, IPacketReader reader) => true;
		public void InitializeRemoteProperties() { }
		public void IgnoreSyncReliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticReliable(IPacketReader reader) { }
		public void IgnoreSyncUnreliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticUnreliable(IPacketReader reader) { }
	}
}
#pragma warning restore CS0649
