/*
 * Generated File : Master_TestValue64
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Collections.Generic;
using CT.Common.DataType;
using CT.Common.Serialization;
using CT.Common.Serialization.Type;
using CT.Common.Synchronizations;
using CT.Common.Tools.Collections;
using CTS.Instance.Synchronizations;

namespace CTS.Instance.SyncObjects
{
	[Serializable]
	public partial class TestValue64 : MasterNetworkObject
	{
		public override NetworkObjectType Type => NetworkObjectType.TestValue64;
		[SyncVar]
		private int _v0;
		[SyncVar]
		private int _v1;
		[SyncVar]
		private int _v2;
		[SyncVar]
		private int _v4;
		[SyncVar]
		private int _v5;
		[SyncVar]
		private int _v6;
		[SyncVar]
		private int _v7;
		[SyncVar]
		private int _v8;
		[SyncVar]
		private int _v9;
		[SyncVar]
		private int _v10;
		[SyncVar]
		private int _v12;
		[SyncVar]
		private int _v13;
		[SyncVar]
		private int _v15;
		[SyncVar]
		private int _v16;
		[SyncVar]
		private int _v18;
		[SyncVar]
		private int _v19;
		[SyncVar]
		private int _v20;
		[SyncVar]
		private int _v21;
		[SyncVar]
		private int _v23;
		[SyncVar]
		private int _v25;
		[SyncVar]
		private int _v26;
		[SyncVar]
		private int _v27;
		[SyncVar]
		private int _v29;
		[SyncVar]
		private int _v30;
		[SyncVar]
		private int _v31;
		[SyncVar]
		private int _v32;
		[SyncVar]
		private int _v33;
		[SyncVar]
		private int _v35;
		[SyncVar]
		private int _v36;
		[SyncVar]
		private int _v37;
		[SyncVar]
		private int _v38;
		[SyncVar]
		private int _v39;
		[SyncVar]
		private int _v40;
		[SyncVar]
		private int _v43;
		[SyncVar]
		private int _v44;
		[SyncVar]
		private int _v45;
		[SyncVar]
		private int _v46;
		[SyncVar]
		private int _v47;
		[SyncVar]
		private int _v48;
		[SyncVar]
		private int _v50;
		[SyncVar]
		private int _v51;
		[SyncVar]
		private int _v52;
		[SyncVar]
		private int _v53;
		[SyncVar]
		private int _v55;
		[SyncVar]
		private int _v56;
		[SyncVar]
		private int _v57;
		[SyncVar]
		private int _v58;
		[SyncVar]
		private int _v59;
		[SyncVar]
		private int _v60;
		[SyncVar]
		private int _v62;
		[SyncVar]
		private int _v63;
		[SyncVar(SyncType.Unreliable)]
		private int _uv0;
		[SyncVar(SyncType.Unreliable)]
		private int _uv1;
		[SyncVar(SyncType.Unreliable)]
		private int _uv2;
		[SyncVar(SyncType.Unreliable)]
		private int _uv4;
		[SyncVar(SyncType.Unreliable)]
		private int _uv5;
		[SyncVar(SyncType.Unreliable)]
		private int _uv6;
		[SyncVar(SyncType.Unreliable)]
		private int _uv7;
		[SyncVar(SyncType.Unreliable)]
		private int _uv8;
		[SyncVar(SyncType.Unreliable)]
		private int _uv9;
		[SyncVar(SyncType.Unreliable)]
		private int _uv10;
		[SyncVar(SyncType.Unreliable)]
		private int _uv12;
		[SyncVar(SyncType.Unreliable)]
		private int _uv13;
		[SyncVar(SyncType.Unreliable)]
		private int _uv15;
		[SyncVar(SyncType.Unreliable)]
		private int _uv16;
		[SyncVar(SyncType.Unreliable)]
		private int _uv18;
		[SyncVar(SyncType.Unreliable)]
		private int _uv19;
		[SyncVar(SyncType.Unreliable)]
		private int _uv20;
		[SyncVar(SyncType.Unreliable)]
		private int _uv21;
		[SyncVar(SyncType.Unreliable)]
		private int _uv23;
		[SyncVar(SyncType.Unreliable)]
		private int _uv25;
		[SyncVar(SyncType.Unreliable)]
		private int _uv26;
		[SyncVar(SyncType.Unreliable)]
		private int _uv27;
		[SyncVar(SyncType.Unreliable)]
		private int _uv29;
		[SyncVar(SyncType.Unreliable)]
		private int _uv30;
		[SyncVar(SyncType.Unreliable)]
		private int _uv31;
		[SyncVar(SyncType.Unreliable)]
		private int _uv32;
		[SyncVar(SyncType.Unreliable)]
		private int _uv33;
		[SyncVar(SyncType.Unreliable)]
		private int _uv35;
		[SyncVar(SyncType.Unreliable)]
		private int _uv36;
		[SyncVar(SyncType.Unreliable)]
		private int _uv37;
		[SyncVar(SyncType.Unreliable)]
		private int _uv38;
		[SyncVar(SyncType.Unreliable)]
		private int _uv39;
		[SyncVar(SyncType.Unreliable)]
		private int _uv40;
		[SyncVar(SyncType.Unreliable)]
		private int _uv43;
		[SyncVar(SyncType.Unreliable)]
		private int _uv44;
		[SyncVar(SyncType.Unreliable)]
		private int _uv45;
		[SyncVar(SyncType.Unreliable)]
		private int _uv46;
		[SyncVar(SyncType.Unreliable)]
		private int _uv47;
		[SyncVar(SyncType.Unreliable)]
		private int _uv48;
		[SyncVar(SyncType.Unreliable)]
		private int _uv50;
		[SyncVar(SyncType.Unreliable)]
		private int _uv51;
		[SyncVar(SyncType.Unreliable)]
		private int _uv52;
		[SyncVar(SyncType.Unreliable)]
		private int _uv53;
		[SyncVar(SyncType.Unreliable)]
		private int _uv55;
		[SyncVar(SyncType.Unreliable)]
		private int _uv56;
		[SyncVar(SyncType.Unreliable)]
		private int _uv57;
		[SyncVar(SyncType.Unreliable)]
		private int _uv58;
		[SyncVar(SyncType.Unreliable)]
		private int _uv59;
		[SyncVar(SyncType.Unreliable)]
		private int _uv60;
		[SyncVar(SyncType.Unreliable)]
		private int _uv62;
		[SyncVar(SyncType.Unreliable)]
		private int _uv63;
		[SyncRpc]
		public partial void f3(int a);
		[SyncRpc]
		public partial void f14(int a);
		[SyncRpc]
		public partial void f17(int a);
		[SyncRpc]
		public partial void f22(int a);
		[SyncRpc]
		public partial void f24(int a);
		[SyncRpc]
		public partial void f28(int a);
		[SyncRpc]
		public partial void f34(int a);
		[SyncRpc]
		public partial void f41(int a);
		[SyncRpc]
		public partial void f42(int a);
		[SyncRpc]
		public partial void f49(int a);
		[SyncRpc]
		public partial void f54(int a);
		[SyncRpc]
		public partial void f61(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf3(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf14(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf17(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf22(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf24(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf28(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf34(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf41(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf42(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf49(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf54(int a);
		[SyncRpc(SyncType.Unreliable)]
		public partial void uf61(int a);
		private BitmaskByte _dirtyReliable_0 = new();
		private BitmaskByte _dirtyReliable_1 = new();
		private BitmaskByte _dirtyReliable_2 = new();
		private BitmaskByte _dirtyReliable_3 = new();
		private BitmaskByte _dirtyReliable_4 = new();
		private BitmaskByte _dirtyReliable_5 = new();
		private BitmaskByte _dirtyReliable_6 = new();
		private BitmaskByte _dirtyReliable_7 = new();
		private BitmaskByte _dirtyUnreliable_0 = new();
		private BitmaskByte _dirtyUnreliable_1 = new();
		private BitmaskByte _dirtyUnreliable_2 = new();
		private BitmaskByte _dirtyUnreliable_3 = new();
		private BitmaskByte _dirtyUnreliable_4 = new();
		private BitmaskByte _dirtyUnreliable_5 = new();
		private BitmaskByte _dirtyUnreliable_6 = new();
		private BitmaskByte _dirtyUnreliable_7 = new();
		public override bool IsDirtyReliable
		{
			get
			{
				bool isDirty = false;
				isDirty |= _dirtyReliable_0.AnyTrue();
				isDirty |= _dirtyReliable_1.AnyTrue();
				isDirty |= _dirtyReliable_2.AnyTrue();
				isDirty |= _dirtyReliable_3.AnyTrue();
				isDirty |= _dirtyReliable_4.AnyTrue();
				isDirty |= _dirtyReliable_5.AnyTrue();
				isDirty |= _dirtyReliable_6.AnyTrue();
				isDirty |= _dirtyReliable_7.AnyTrue();
				return isDirty;
			}
		}
		public override bool IsDirtyUnreliable
		{
			get
			{
				bool isDirty = false;
				isDirty |= _dirtyUnreliable_0.AnyTrue();
				isDirty |= _dirtyUnreliable_1.AnyTrue();
				isDirty |= _dirtyUnreliable_2.AnyTrue();
				isDirty |= _dirtyUnreliable_3.AnyTrue();
				isDirty |= _dirtyUnreliable_4.AnyTrue();
				isDirty |= _dirtyUnreliable_5.AnyTrue();
				isDirty |= _dirtyUnreliable_6.AnyTrue();
				isDirty |= _dirtyUnreliable_7.AnyTrue();
				return isDirty;
			}
		}
		public int V0
		{
			get => _v0;
			set
			{
				if (_v0 == value) return;
				_v0 = value;
				_dirtyReliable_0[0] = true;
			}
		}
		public int V1
		{
			get => _v1;
			set
			{
				if (_v1 == value) return;
				_v1 = value;
				_dirtyReliable_0[1] = true;
			}
		}
		public int V2
		{
			get => _v2;
			set
			{
				if (_v2 == value) return;
				_v2 = value;
				_dirtyReliable_0[2] = true;
			}
		}
		public int V4
		{
			get => _v4;
			set
			{
				if (_v4 == value) return;
				_v4 = value;
				_dirtyReliable_0[3] = true;
			}
		}
		public int V5
		{
			get => _v5;
			set
			{
				if (_v5 == value) return;
				_v5 = value;
				_dirtyReliable_0[4] = true;
			}
		}
		public int V6
		{
			get => _v6;
			set
			{
				if (_v6 == value) return;
				_v6 = value;
				_dirtyReliable_0[5] = true;
			}
		}
		public int V7
		{
			get => _v7;
			set
			{
				if (_v7 == value) return;
				_v7 = value;
				_dirtyReliable_0[6] = true;
			}
		}
		public int V8
		{
			get => _v8;
			set
			{
				if (_v8 == value) return;
				_v8 = value;
				_dirtyReliable_0[7] = true;
			}
		}
		public int V9
		{
			get => _v9;
			set
			{
				if (_v9 == value) return;
				_v9 = value;
				_dirtyReliable_1[0] = true;
			}
		}
		public int V10
		{
			get => _v10;
			set
			{
				if (_v10 == value) return;
				_v10 = value;
				_dirtyReliable_1[1] = true;
			}
		}
		public int V12
		{
			get => _v12;
			set
			{
				if (_v12 == value) return;
				_v12 = value;
				_dirtyReliable_1[2] = true;
			}
		}
		public int V13
		{
			get => _v13;
			set
			{
				if (_v13 == value) return;
				_v13 = value;
				_dirtyReliable_1[3] = true;
			}
		}
		public int V15
		{
			get => _v15;
			set
			{
				if (_v15 == value) return;
				_v15 = value;
				_dirtyReliable_1[4] = true;
			}
		}
		public int V16
		{
			get => _v16;
			set
			{
				if (_v16 == value) return;
				_v16 = value;
				_dirtyReliable_1[5] = true;
			}
		}
		public int V18
		{
			get => _v18;
			set
			{
				if (_v18 == value) return;
				_v18 = value;
				_dirtyReliable_1[6] = true;
			}
		}
		public int V19
		{
			get => _v19;
			set
			{
				if (_v19 == value) return;
				_v19 = value;
				_dirtyReliable_1[7] = true;
			}
		}
		public int V20
		{
			get => _v20;
			set
			{
				if (_v20 == value) return;
				_v20 = value;
				_dirtyReliable_2[0] = true;
			}
		}
		public int V21
		{
			get => _v21;
			set
			{
				if (_v21 == value) return;
				_v21 = value;
				_dirtyReliable_2[1] = true;
			}
		}
		public int V23
		{
			get => _v23;
			set
			{
				if (_v23 == value) return;
				_v23 = value;
				_dirtyReliable_2[2] = true;
			}
		}
		public int V25
		{
			get => _v25;
			set
			{
				if (_v25 == value) return;
				_v25 = value;
				_dirtyReliable_2[3] = true;
			}
		}
		public int V26
		{
			get => _v26;
			set
			{
				if (_v26 == value) return;
				_v26 = value;
				_dirtyReliable_2[4] = true;
			}
		}
		public int V27
		{
			get => _v27;
			set
			{
				if (_v27 == value) return;
				_v27 = value;
				_dirtyReliable_2[5] = true;
			}
		}
		public int V29
		{
			get => _v29;
			set
			{
				if (_v29 == value) return;
				_v29 = value;
				_dirtyReliable_2[6] = true;
			}
		}
		public int V30
		{
			get => _v30;
			set
			{
				if (_v30 == value) return;
				_v30 = value;
				_dirtyReliable_2[7] = true;
			}
		}
		public int V31
		{
			get => _v31;
			set
			{
				if (_v31 == value) return;
				_v31 = value;
				_dirtyReliable_3[0] = true;
			}
		}
		public int V32
		{
			get => _v32;
			set
			{
				if (_v32 == value) return;
				_v32 = value;
				_dirtyReliable_3[1] = true;
			}
		}
		public int V33
		{
			get => _v33;
			set
			{
				if (_v33 == value) return;
				_v33 = value;
				_dirtyReliable_3[2] = true;
			}
		}
		public int V35
		{
			get => _v35;
			set
			{
				if (_v35 == value) return;
				_v35 = value;
				_dirtyReliable_3[3] = true;
			}
		}
		public int V36
		{
			get => _v36;
			set
			{
				if (_v36 == value) return;
				_v36 = value;
				_dirtyReliable_3[4] = true;
			}
		}
		public int V37
		{
			get => _v37;
			set
			{
				if (_v37 == value) return;
				_v37 = value;
				_dirtyReliable_3[5] = true;
			}
		}
		public int V38
		{
			get => _v38;
			set
			{
				if (_v38 == value) return;
				_v38 = value;
				_dirtyReliable_3[6] = true;
			}
		}
		public int V39
		{
			get => _v39;
			set
			{
				if (_v39 == value) return;
				_v39 = value;
				_dirtyReliable_3[7] = true;
			}
		}
		public int V40
		{
			get => _v40;
			set
			{
				if (_v40 == value) return;
				_v40 = value;
				_dirtyReliable_4[0] = true;
			}
		}
		public int V43
		{
			get => _v43;
			set
			{
				if (_v43 == value) return;
				_v43 = value;
				_dirtyReliable_4[1] = true;
			}
		}
		public int V44
		{
			get => _v44;
			set
			{
				if (_v44 == value) return;
				_v44 = value;
				_dirtyReliable_4[2] = true;
			}
		}
		public int V45
		{
			get => _v45;
			set
			{
				if (_v45 == value) return;
				_v45 = value;
				_dirtyReliable_4[3] = true;
			}
		}
		public int V46
		{
			get => _v46;
			set
			{
				if (_v46 == value) return;
				_v46 = value;
				_dirtyReliable_4[4] = true;
			}
		}
		public int V47
		{
			get => _v47;
			set
			{
				if (_v47 == value) return;
				_v47 = value;
				_dirtyReliable_4[5] = true;
			}
		}
		public int V48
		{
			get => _v48;
			set
			{
				if (_v48 == value) return;
				_v48 = value;
				_dirtyReliable_4[6] = true;
			}
		}
		public int V50
		{
			get => _v50;
			set
			{
				if (_v50 == value) return;
				_v50 = value;
				_dirtyReliable_4[7] = true;
			}
		}
		public int V51
		{
			get => _v51;
			set
			{
				if (_v51 == value) return;
				_v51 = value;
				_dirtyReliable_5[0] = true;
			}
		}
		public int V52
		{
			get => _v52;
			set
			{
				if (_v52 == value) return;
				_v52 = value;
				_dirtyReliable_5[1] = true;
			}
		}
		public int V53
		{
			get => _v53;
			set
			{
				if (_v53 == value) return;
				_v53 = value;
				_dirtyReliable_5[2] = true;
			}
		}
		public int V55
		{
			get => _v55;
			set
			{
				if (_v55 == value) return;
				_v55 = value;
				_dirtyReliable_5[3] = true;
			}
		}
		public int V56
		{
			get => _v56;
			set
			{
				if (_v56 == value) return;
				_v56 = value;
				_dirtyReliable_5[4] = true;
			}
		}
		public int V57
		{
			get => _v57;
			set
			{
				if (_v57 == value) return;
				_v57 = value;
				_dirtyReliable_5[5] = true;
			}
		}
		public int V58
		{
			get => _v58;
			set
			{
				if (_v58 == value) return;
				_v58 = value;
				_dirtyReliable_5[6] = true;
			}
		}
		public int V59
		{
			get => _v59;
			set
			{
				if (_v59 == value) return;
				_v59 = value;
				_dirtyReliable_5[7] = true;
			}
		}
		public int V60
		{
			get => _v60;
			set
			{
				if (_v60 == value) return;
				_v60 = value;
				_dirtyReliable_6[0] = true;
			}
		}
		public int V62
		{
			get => _v62;
			set
			{
				if (_v62 == value) return;
				_v62 = value;
				_dirtyReliable_6[1] = true;
			}
		}
		public int V63
		{
			get => _v63;
			set
			{
				if (_v63 == value) return;
				_v63 = value;
				_dirtyReliable_6[2] = true;
			}
		}
		public partial void f3(int a)
		{
			f3Callstack.Enqueue(a);
			_dirtyReliable_6[3] = true;
		}
		private Queue<int> f3Callstack = new();
		public partial void f14(int a)
		{
			f14Callstack.Enqueue(a);
			_dirtyReliable_6[4] = true;
		}
		private Queue<int> f14Callstack = new();
		public partial void f17(int a)
		{
			f17Callstack.Enqueue(a);
			_dirtyReliable_6[5] = true;
		}
		private Queue<int> f17Callstack = new();
		public partial void f22(int a)
		{
			f22Callstack.Enqueue(a);
			_dirtyReliable_6[6] = true;
		}
		private Queue<int> f22Callstack = new();
		public partial void f24(int a)
		{
			f24Callstack.Enqueue(a);
			_dirtyReliable_6[7] = true;
		}
		private Queue<int> f24Callstack = new();
		public partial void f28(int a)
		{
			f28Callstack.Enqueue(a);
			_dirtyReliable_7[0] = true;
		}
		private Queue<int> f28Callstack = new();
		public partial void f34(int a)
		{
			f34Callstack.Enqueue(a);
			_dirtyReliable_7[1] = true;
		}
		private Queue<int> f34Callstack = new();
		public partial void f41(int a)
		{
			f41Callstack.Enqueue(a);
			_dirtyReliable_7[2] = true;
		}
		private Queue<int> f41Callstack = new();
		public partial void f42(int a)
		{
			f42Callstack.Enqueue(a);
			_dirtyReliable_7[3] = true;
		}
		private Queue<int> f42Callstack = new();
		public partial void f49(int a)
		{
			f49Callstack.Enqueue(a);
			_dirtyReliable_7[4] = true;
		}
		private Queue<int> f49Callstack = new();
		public partial void f54(int a)
		{
			f54Callstack.Enqueue(a);
			_dirtyReliable_7[5] = true;
		}
		private Queue<int> f54Callstack = new();
		public partial void f61(int a)
		{
			f61Callstack.Enqueue(a);
			_dirtyReliable_7[6] = true;
		}
		private Queue<int> f61Callstack = new();
		public int Uv0
		{
			get => _uv0;
			set
			{
				if (_uv0 == value) return;
				_uv0 = value;
				_dirtyUnreliable_0[0] = true;
			}
		}
		public int Uv1
		{
			get => _uv1;
			set
			{
				if (_uv1 == value) return;
				_uv1 = value;
				_dirtyUnreliable_0[1] = true;
			}
		}
		public int Uv2
		{
			get => _uv2;
			set
			{
				if (_uv2 == value) return;
				_uv2 = value;
				_dirtyUnreliable_0[2] = true;
			}
		}
		public int Uv4
		{
			get => _uv4;
			set
			{
				if (_uv4 == value) return;
				_uv4 = value;
				_dirtyUnreliable_0[3] = true;
			}
		}
		public int Uv5
		{
			get => _uv5;
			set
			{
				if (_uv5 == value) return;
				_uv5 = value;
				_dirtyUnreliable_0[4] = true;
			}
		}
		public int Uv6
		{
			get => _uv6;
			set
			{
				if (_uv6 == value) return;
				_uv6 = value;
				_dirtyUnreliable_0[5] = true;
			}
		}
		public int Uv7
		{
			get => _uv7;
			set
			{
				if (_uv7 == value) return;
				_uv7 = value;
				_dirtyUnreliable_0[6] = true;
			}
		}
		public int Uv8
		{
			get => _uv8;
			set
			{
				if (_uv8 == value) return;
				_uv8 = value;
				_dirtyUnreliable_0[7] = true;
			}
		}
		public int Uv9
		{
			get => _uv9;
			set
			{
				if (_uv9 == value) return;
				_uv9 = value;
				_dirtyUnreliable_1[0] = true;
			}
		}
		public int Uv10
		{
			get => _uv10;
			set
			{
				if (_uv10 == value) return;
				_uv10 = value;
				_dirtyUnreliable_1[1] = true;
			}
		}
		public int Uv12
		{
			get => _uv12;
			set
			{
				if (_uv12 == value) return;
				_uv12 = value;
				_dirtyUnreliable_1[2] = true;
			}
		}
		public int Uv13
		{
			get => _uv13;
			set
			{
				if (_uv13 == value) return;
				_uv13 = value;
				_dirtyUnreliable_1[3] = true;
			}
		}
		public int Uv15
		{
			get => _uv15;
			set
			{
				if (_uv15 == value) return;
				_uv15 = value;
				_dirtyUnreliable_1[4] = true;
			}
		}
		public int Uv16
		{
			get => _uv16;
			set
			{
				if (_uv16 == value) return;
				_uv16 = value;
				_dirtyUnreliable_1[5] = true;
			}
		}
		public int Uv18
		{
			get => _uv18;
			set
			{
				if (_uv18 == value) return;
				_uv18 = value;
				_dirtyUnreliable_1[6] = true;
			}
		}
		public int Uv19
		{
			get => _uv19;
			set
			{
				if (_uv19 == value) return;
				_uv19 = value;
				_dirtyUnreliable_1[7] = true;
			}
		}
		public int Uv20
		{
			get => _uv20;
			set
			{
				if (_uv20 == value) return;
				_uv20 = value;
				_dirtyUnreliable_2[0] = true;
			}
		}
		public int Uv21
		{
			get => _uv21;
			set
			{
				if (_uv21 == value) return;
				_uv21 = value;
				_dirtyUnreliable_2[1] = true;
			}
		}
		public int Uv23
		{
			get => _uv23;
			set
			{
				if (_uv23 == value) return;
				_uv23 = value;
				_dirtyUnreliable_2[2] = true;
			}
		}
		public int Uv25
		{
			get => _uv25;
			set
			{
				if (_uv25 == value) return;
				_uv25 = value;
				_dirtyUnreliable_2[3] = true;
			}
		}
		public int Uv26
		{
			get => _uv26;
			set
			{
				if (_uv26 == value) return;
				_uv26 = value;
				_dirtyUnreliable_2[4] = true;
			}
		}
		public int Uv27
		{
			get => _uv27;
			set
			{
				if (_uv27 == value) return;
				_uv27 = value;
				_dirtyUnreliable_2[5] = true;
			}
		}
		public int Uv29
		{
			get => _uv29;
			set
			{
				if (_uv29 == value) return;
				_uv29 = value;
				_dirtyUnreliable_2[6] = true;
			}
		}
		public int Uv30
		{
			get => _uv30;
			set
			{
				if (_uv30 == value) return;
				_uv30 = value;
				_dirtyUnreliable_2[7] = true;
			}
		}
		public int Uv31
		{
			get => _uv31;
			set
			{
				if (_uv31 == value) return;
				_uv31 = value;
				_dirtyUnreliable_3[0] = true;
			}
		}
		public int Uv32
		{
			get => _uv32;
			set
			{
				if (_uv32 == value) return;
				_uv32 = value;
				_dirtyUnreliable_3[1] = true;
			}
		}
		public int Uv33
		{
			get => _uv33;
			set
			{
				if (_uv33 == value) return;
				_uv33 = value;
				_dirtyUnreliable_3[2] = true;
			}
		}
		public int Uv35
		{
			get => _uv35;
			set
			{
				if (_uv35 == value) return;
				_uv35 = value;
				_dirtyUnreliable_3[3] = true;
			}
		}
		public int Uv36
		{
			get => _uv36;
			set
			{
				if (_uv36 == value) return;
				_uv36 = value;
				_dirtyUnreliable_3[4] = true;
			}
		}
		public int Uv37
		{
			get => _uv37;
			set
			{
				if (_uv37 == value) return;
				_uv37 = value;
				_dirtyUnreliable_3[5] = true;
			}
		}
		public int Uv38
		{
			get => _uv38;
			set
			{
				if (_uv38 == value) return;
				_uv38 = value;
				_dirtyUnreliable_3[6] = true;
			}
		}
		public int Uv39
		{
			get => _uv39;
			set
			{
				if (_uv39 == value) return;
				_uv39 = value;
				_dirtyUnreliable_3[7] = true;
			}
		}
		public int Uv40
		{
			get => _uv40;
			set
			{
				if (_uv40 == value) return;
				_uv40 = value;
				_dirtyUnreliable_4[0] = true;
			}
		}
		public int Uv43
		{
			get => _uv43;
			set
			{
				if (_uv43 == value) return;
				_uv43 = value;
				_dirtyUnreliable_4[1] = true;
			}
		}
		public int Uv44
		{
			get => _uv44;
			set
			{
				if (_uv44 == value) return;
				_uv44 = value;
				_dirtyUnreliable_4[2] = true;
			}
		}
		public int Uv45
		{
			get => _uv45;
			set
			{
				if (_uv45 == value) return;
				_uv45 = value;
				_dirtyUnreliable_4[3] = true;
			}
		}
		public int Uv46
		{
			get => _uv46;
			set
			{
				if (_uv46 == value) return;
				_uv46 = value;
				_dirtyUnreliable_4[4] = true;
			}
		}
		public int Uv47
		{
			get => _uv47;
			set
			{
				if (_uv47 == value) return;
				_uv47 = value;
				_dirtyUnreliable_4[5] = true;
			}
		}
		public int Uv48
		{
			get => _uv48;
			set
			{
				if (_uv48 == value) return;
				_uv48 = value;
				_dirtyUnreliable_4[6] = true;
			}
		}
		public int Uv50
		{
			get => _uv50;
			set
			{
				if (_uv50 == value) return;
				_uv50 = value;
				_dirtyUnreliable_4[7] = true;
			}
		}
		public int Uv51
		{
			get => _uv51;
			set
			{
				if (_uv51 == value) return;
				_uv51 = value;
				_dirtyUnreliable_5[0] = true;
			}
		}
		public int Uv52
		{
			get => _uv52;
			set
			{
				if (_uv52 == value) return;
				_uv52 = value;
				_dirtyUnreliable_5[1] = true;
			}
		}
		public int Uv53
		{
			get => _uv53;
			set
			{
				if (_uv53 == value) return;
				_uv53 = value;
				_dirtyUnreliable_5[2] = true;
			}
		}
		public int Uv55
		{
			get => _uv55;
			set
			{
				if (_uv55 == value) return;
				_uv55 = value;
				_dirtyUnreliable_5[3] = true;
			}
		}
		public int Uv56
		{
			get => _uv56;
			set
			{
				if (_uv56 == value) return;
				_uv56 = value;
				_dirtyUnreliable_5[4] = true;
			}
		}
		public int Uv57
		{
			get => _uv57;
			set
			{
				if (_uv57 == value) return;
				_uv57 = value;
				_dirtyUnreliable_5[5] = true;
			}
		}
		public int Uv58
		{
			get => _uv58;
			set
			{
				if (_uv58 == value) return;
				_uv58 = value;
				_dirtyUnreliable_5[6] = true;
			}
		}
		public int Uv59
		{
			get => _uv59;
			set
			{
				if (_uv59 == value) return;
				_uv59 = value;
				_dirtyUnreliable_5[7] = true;
			}
		}
		public int Uv60
		{
			get => _uv60;
			set
			{
				if (_uv60 == value) return;
				_uv60 = value;
				_dirtyUnreliable_6[0] = true;
			}
		}
		public int Uv62
		{
			get => _uv62;
			set
			{
				if (_uv62 == value) return;
				_uv62 = value;
				_dirtyUnreliable_6[1] = true;
			}
		}
		public int Uv63
		{
			get => _uv63;
			set
			{
				if (_uv63 == value) return;
				_uv63 = value;
				_dirtyUnreliable_6[2] = true;
			}
		}
		public partial void uf3(int a)
		{
			uf3Callstack.Enqueue(a);
			_dirtyUnreliable_6[3] = true;
		}
		private Queue<int> uf3Callstack = new();
		public partial void uf14(int a)
		{
			uf14Callstack.Enqueue(a);
			_dirtyUnreliable_6[4] = true;
		}
		private Queue<int> uf14Callstack = new();
		public partial void uf17(int a)
		{
			uf17Callstack.Enqueue(a);
			_dirtyUnreliable_6[5] = true;
		}
		private Queue<int> uf17Callstack = new();
		public partial void uf22(int a)
		{
			uf22Callstack.Enqueue(a);
			_dirtyUnreliable_6[6] = true;
		}
		private Queue<int> uf22Callstack = new();
		public partial void uf24(int a)
		{
			uf24Callstack.Enqueue(a);
			_dirtyUnreliable_6[7] = true;
		}
		private Queue<int> uf24Callstack = new();
		public partial void uf28(int a)
		{
			uf28Callstack.Enqueue(a);
			_dirtyUnreliable_7[0] = true;
		}
		private Queue<int> uf28Callstack = new();
		public partial void uf34(int a)
		{
			uf34Callstack.Enqueue(a);
			_dirtyUnreliable_7[1] = true;
		}
		private Queue<int> uf34Callstack = new();
		public partial void uf41(int a)
		{
			uf41Callstack.Enqueue(a);
			_dirtyUnreliable_7[2] = true;
		}
		private Queue<int> uf41Callstack = new();
		public partial void uf42(int a)
		{
			uf42Callstack.Enqueue(a);
			_dirtyUnreliable_7[3] = true;
		}
		private Queue<int> uf42Callstack = new();
		public partial void uf49(int a)
		{
			uf49Callstack.Enqueue(a);
			_dirtyUnreliable_7[4] = true;
		}
		private Queue<int> uf49Callstack = new();
		public partial void uf54(int a)
		{
			uf54Callstack.Enqueue(a);
			_dirtyUnreliable_7[5] = true;
		}
		private Queue<int> uf54Callstack = new();
		public partial void uf61(int a)
		{
			uf61Callstack.Enqueue(a);
			_dirtyUnreliable_7[6] = true;
		}
		private Queue<int> uf61Callstack = new();
		public override void ClearDirtyReliable()
		{
			_dirtyReliable_0.Clear();
			_dirtyReliable_1.Clear();
			_dirtyReliable_2.Clear();
			_dirtyReliable_3.Clear();
			_dirtyReliable_4.Clear();
			_dirtyReliable_5.Clear();
			_dirtyReliable_6.Clear();
			_dirtyReliable_7.Clear();
		}
		public override void ClearDirtyUnreliable()
		{
			_dirtyUnreliable_0.Clear();
			_dirtyUnreliable_1.Clear();
			_dirtyUnreliable_2.Clear();
			_dirtyUnreliable_3.Clear();
			_dirtyUnreliable_4.Clear();
			_dirtyUnreliable_5.Clear();
			_dirtyUnreliable_6.Clear();
			_dirtyUnreliable_7.Clear();
		}
		public override void SerializeSyncReliable(PacketWriter writer)
		{
			BitmaskByte masterDirty = new BitmaskByte();
			masterDirty[0] = _dirtyReliable_0.AnyTrue();
			masterDirty[1] = _dirtyReliable_1.AnyTrue();
			masterDirty[2] = _dirtyReliable_2.AnyTrue();
			masterDirty[3] = _dirtyReliable_3.AnyTrue();
			masterDirty[4] = _dirtyReliable_4.AnyTrue();
			masterDirty[5] = _dirtyReliable_5.AnyTrue();
			masterDirty[6] = _dirtyReliable_6.AnyTrue();
			masterDirty[7] = _dirtyReliable_7.AnyTrue();
			masterDirty.Serialize(writer);
			if (masterDirty[0])
			{
				_dirtyReliable_0.Serialize(writer);
				if (_dirtyReliable_0[0])
				{
					writer.Put(_v0);
				}
				if (_dirtyReliable_0[1])
				{
					writer.Put(_v1);
				}
				if (_dirtyReliable_0[2])
				{
					writer.Put(_v2);
				}
				if (_dirtyReliable_0[3])
				{
					writer.Put(_v4);
				}
				if (_dirtyReliable_0[4])
				{
					writer.Put(_v5);
				}
				if (_dirtyReliable_0[5])
				{
					writer.Put(_v6);
				}
				if (_dirtyReliable_0[6])
				{
					writer.Put(_v7);
				}
				if (_dirtyReliable_0[7])
				{
					writer.Put(_v8);
				}
			}
			if (masterDirty[1])
			{
				_dirtyReliable_1.Serialize(writer);
				if (_dirtyReliable_1[0])
				{
					writer.Put(_v9);
				}
				if (_dirtyReliable_1[1])
				{
					writer.Put(_v10);
				}
				if (_dirtyReliable_1[2])
				{
					writer.Put(_v12);
				}
				if (_dirtyReliable_1[3])
				{
					writer.Put(_v13);
				}
				if (_dirtyReliable_1[4])
				{
					writer.Put(_v15);
				}
				if (_dirtyReliable_1[5])
				{
					writer.Put(_v16);
				}
				if (_dirtyReliable_1[6])
				{
					writer.Put(_v18);
				}
				if (_dirtyReliable_1[7])
				{
					writer.Put(_v19);
				}
			}
			if (masterDirty[2])
			{
				_dirtyReliable_2.Serialize(writer);
				if (_dirtyReliable_2[0])
				{
					writer.Put(_v20);
				}
				if (_dirtyReliable_2[1])
				{
					writer.Put(_v21);
				}
				if (_dirtyReliable_2[2])
				{
					writer.Put(_v23);
				}
				if (_dirtyReliable_2[3])
				{
					writer.Put(_v25);
				}
				if (_dirtyReliable_2[4])
				{
					writer.Put(_v26);
				}
				if (_dirtyReliable_2[5])
				{
					writer.Put(_v27);
				}
				if (_dirtyReliable_2[6])
				{
					writer.Put(_v29);
				}
				if (_dirtyReliable_2[7])
				{
					writer.Put(_v30);
				}
			}
			if (masterDirty[3])
			{
				_dirtyReliable_3.Serialize(writer);
				if (_dirtyReliable_3[0])
				{
					writer.Put(_v31);
				}
				if (_dirtyReliable_3[1])
				{
					writer.Put(_v32);
				}
				if (_dirtyReliable_3[2])
				{
					writer.Put(_v33);
				}
				if (_dirtyReliable_3[3])
				{
					writer.Put(_v35);
				}
				if (_dirtyReliable_3[4])
				{
					writer.Put(_v36);
				}
				if (_dirtyReliable_3[5])
				{
					writer.Put(_v37);
				}
				if (_dirtyReliable_3[6])
				{
					writer.Put(_v38);
				}
				if (_dirtyReliable_3[7])
				{
					writer.Put(_v39);
				}
			}
			if (masterDirty[4])
			{
				_dirtyReliable_4.Serialize(writer);
				if (_dirtyReliable_4[0])
				{
					writer.Put(_v40);
				}
				if (_dirtyReliable_4[1])
				{
					writer.Put(_v43);
				}
				if (_dirtyReliable_4[2])
				{
					writer.Put(_v44);
				}
				if (_dirtyReliable_4[3])
				{
					writer.Put(_v45);
				}
				if (_dirtyReliable_4[4])
				{
					writer.Put(_v46);
				}
				if (_dirtyReliable_4[5])
				{
					writer.Put(_v47);
				}
				if (_dirtyReliable_4[6])
				{
					writer.Put(_v48);
				}
				if (_dirtyReliable_4[7])
				{
					writer.Put(_v50);
				}
			}
			if (masterDirty[5])
			{
				_dirtyReliable_5.Serialize(writer);
				if (_dirtyReliable_5[0])
				{
					writer.Put(_v51);
				}
				if (_dirtyReliable_5[1])
				{
					writer.Put(_v52);
				}
				if (_dirtyReliable_5[2])
				{
					writer.Put(_v53);
				}
				if (_dirtyReliable_5[3])
				{
					writer.Put(_v55);
				}
				if (_dirtyReliable_5[4])
				{
					writer.Put(_v56);
				}
				if (_dirtyReliable_5[5])
				{
					writer.Put(_v57);
				}
				if (_dirtyReliable_5[6])
				{
					writer.Put(_v58);
				}
				if (_dirtyReliable_5[7])
				{
					writer.Put(_v59);
				}
			}
			if (masterDirty[6])
			{
				_dirtyReliable_6.Serialize(writer);
				if (_dirtyReliable_6[0])
				{
					writer.Put(_v60);
				}
				if (_dirtyReliable_6[1])
				{
					writer.Put(_v62);
				}
				if (_dirtyReliable_6[2])
				{
					writer.Put(_v63);
				}
				if (_dirtyReliable_6[3])
				{
					byte count = (byte)f3Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f3Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_6[4])
				{
					byte count = (byte)f14Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f14Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_6[5])
				{
					byte count = (byte)f17Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f17Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_6[6])
				{
					byte count = (byte)f22Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f22Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_6[7])
				{
					byte count = (byte)f24Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f24Callstack.Dequeue();
						writer.Put(arg);
					}
				}
			}
			if (masterDirty[7])
			{
				_dirtyReliable_7.Serialize(writer);
				if (_dirtyReliable_7[0])
				{
					byte count = (byte)f28Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f28Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[1])
				{
					byte count = (byte)f34Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f34Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[2])
				{
					byte count = (byte)f41Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f41Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[3])
				{
					byte count = (byte)f42Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f42Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[4])
				{
					byte count = (byte)f49Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f49Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[5])
				{
					byte count = (byte)f54Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f54Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyReliable_7[6])
				{
					byte count = (byte)f61Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = f61Callstack.Dequeue();
						writer.Put(arg);
					}
				}
			}
		}
		public override void SerializeSyncUnreliable(PacketWriter writer)
		{
			BitmaskByte masterDirty = new BitmaskByte();
			masterDirty[0] = _dirtyUnreliable_0.AnyTrue();
			masterDirty[1] = _dirtyUnreliable_1.AnyTrue();
			masterDirty[2] = _dirtyUnreliable_2.AnyTrue();
			masterDirty[3] = _dirtyUnreliable_3.AnyTrue();
			masterDirty[4] = _dirtyUnreliable_4.AnyTrue();
			masterDirty[5] = _dirtyUnreliable_5.AnyTrue();
			masterDirty[6] = _dirtyUnreliable_6.AnyTrue();
			masterDirty[7] = _dirtyUnreliable_7.AnyTrue();
			masterDirty.Serialize(writer);
			if (masterDirty[0])
			{
				_dirtyUnreliable_0.Serialize(writer);
				if (_dirtyUnreliable_0[0])
				{
					writer.Put(_uv0);
				}
				if (_dirtyUnreliable_0[1])
				{
					writer.Put(_uv1);
				}
				if (_dirtyUnreliable_0[2])
				{
					writer.Put(_uv2);
				}
				if (_dirtyUnreliable_0[3])
				{
					writer.Put(_uv4);
				}
				if (_dirtyUnreliable_0[4])
				{
					writer.Put(_uv5);
				}
				if (_dirtyUnreliable_0[5])
				{
					writer.Put(_uv6);
				}
				if (_dirtyUnreliable_0[6])
				{
					writer.Put(_uv7);
				}
				if (_dirtyUnreliable_0[7])
				{
					writer.Put(_uv8);
				}
			}
			if (masterDirty[1])
			{
				_dirtyUnreliable_1.Serialize(writer);
				if (_dirtyUnreliable_1[0])
				{
					writer.Put(_uv9);
				}
				if (_dirtyUnreliable_1[1])
				{
					writer.Put(_uv10);
				}
				if (_dirtyUnreliable_1[2])
				{
					writer.Put(_uv12);
				}
				if (_dirtyUnreliable_1[3])
				{
					writer.Put(_uv13);
				}
				if (_dirtyUnreliable_1[4])
				{
					writer.Put(_uv15);
				}
				if (_dirtyUnreliable_1[5])
				{
					writer.Put(_uv16);
				}
				if (_dirtyUnreliable_1[6])
				{
					writer.Put(_uv18);
				}
				if (_dirtyUnreliable_1[7])
				{
					writer.Put(_uv19);
				}
			}
			if (masterDirty[2])
			{
				_dirtyUnreliable_2.Serialize(writer);
				if (_dirtyUnreliable_2[0])
				{
					writer.Put(_uv20);
				}
				if (_dirtyUnreliable_2[1])
				{
					writer.Put(_uv21);
				}
				if (_dirtyUnreliable_2[2])
				{
					writer.Put(_uv23);
				}
				if (_dirtyUnreliable_2[3])
				{
					writer.Put(_uv25);
				}
				if (_dirtyUnreliable_2[4])
				{
					writer.Put(_uv26);
				}
				if (_dirtyUnreliable_2[5])
				{
					writer.Put(_uv27);
				}
				if (_dirtyUnreliable_2[6])
				{
					writer.Put(_uv29);
				}
				if (_dirtyUnreliable_2[7])
				{
					writer.Put(_uv30);
				}
			}
			if (masterDirty[3])
			{
				_dirtyUnreliable_3.Serialize(writer);
				if (_dirtyUnreliable_3[0])
				{
					writer.Put(_uv31);
				}
				if (_dirtyUnreliable_3[1])
				{
					writer.Put(_uv32);
				}
				if (_dirtyUnreliable_3[2])
				{
					writer.Put(_uv33);
				}
				if (_dirtyUnreliable_3[3])
				{
					writer.Put(_uv35);
				}
				if (_dirtyUnreliable_3[4])
				{
					writer.Put(_uv36);
				}
				if (_dirtyUnreliable_3[5])
				{
					writer.Put(_uv37);
				}
				if (_dirtyUnreliable_3[6])
				{
					writer.Put(_uv38);
				}
				if (_dirtyUnreliable_3[7])
				{
					writer.Put(_uv39);
				}
			}
			if (masterDirty[4])
			{
				_dirtyUnreliable_4.Serialize(writer);
				if (_dirtyUnreliable_4[0])
				{
					writer.Put(_uv40);
				}
				if (_dirtyUnreliable_4[1])
				{
					writer.Put(_uv43);
				}
				if (_dirtyUnreliable_4[2])
				{
					writer.Put(_uv44);
				}
				if (_dirtyUnreliable_4[3])
				{
					writer.Put(_uv45);
				}
				if (_dirtyUnreliable_4[4])
				{
					writer.Put(_uv46);
				}
				if (_dirtyUnreliable_4[5])
				{
					writer.Put(_uv47);
				}
				if (_dirtyUnreliable_4[6])
				{
					writer.Put(_uv48);
				}
				if (_dirtyUnreliable_4[7])
				{
					writer.Put(_uv50);
				}
			}
			if (masterDirty[5])
			{
				_dirtyUnreliable_5.Serialize(writer);
				if (_dirtyUnreliable_5[0])
				{
					writer.Put(_uv51);
				}
				if (_dirtyUnreliable_5[1])
				{
					writer.Put(_uv52);
				}
				if (_dirtyUnreliable_5[2])
				{
					writer.Put(_uv53);
				}
				if (_dirtyUnreliable_5[3])
				{
					writer.Put(_uv55);
				}
				if (_dirtyUnreliable_5[4])
				{
					writer.Put(_uv56);
				}
				if (_dirtyUnreliable_5[5])
				{
					writer.Put(_uv57);
				}
				if (_dirtyUnreliable_5[6])
				{
					writer.Put(_uv58);
				}
				if (_dirtyUnreliable_5[7])
				{
					writer.Put(_uv59);
				}
			}
			if (masterDirty[6])
			{
				_dirtyUnreliable_6.Serialize(writer);
				if (_dirtyUnreliable_6[0])
				{
					writer.Put(_uv60);
				}
				if (_dirtyUnreliable_6[1])
				{
					writer.Put(_uv62);
				}
				if (_dirtyUnreliable_6[2])
				{
					writer.Put(_uv63);
				}
				if (_dirtyUnreliable_6[3])
				{
					byte count = (byte)uf3Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf3Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_6[4])
				{
					byte count = (byte)uf14Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf14Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_6[5])
				{
					byte count = (byte)uf17Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf17Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_6[6])
				{
					byte count = (byte)uf22Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf22Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_6[7])
				{
					byte count = (byte)uf24Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf24Callstack.Dequeue();
						writer.Put(arg);
					}
				}
			}
			if (masterDirty[7])
			{
				_dirtyUnreliable_7.Serialize(writer);
				if (_dirtyUnreliable_7[0])
				{
					byte count = (byte)uf28Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf28Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[1])
				{
					byte count = (byte)uf34Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf34Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[2])
				{
					byte count = (byte)uf41Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf41Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[3])
				{
					byte count = (byte)uf42Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf42Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[4])
				{
					byte count = (byte)uf49Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf49Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[5])
				{
					byte count = (byte)uf54Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf54Callstack.Dequeue();
						writer.Put(arg);
					}
				}
				if (_dirtyUnreliable_7[6])
				{
					byte count = (byte)uf61Callstack.Count;
					writer.Put(count);
					for (int i = 0; i < count; i++)
					{
						var arg = uf61Callstack.Dequeue();
						writer.Put(arg);
					}
				}
			}
		}
		public override void SerializeEveryProperty(PacketWriter writer)
		{
			writer.Put(_v0);
			writer.Put(_v1);
			writer.Put(_v2);
			writer.Put(_v4);
			writer.Put(_v5);
			writer.Put(_v6);
			writer.Put(_v7);
			writer.Put(_v8);
			writer.Put(_v9);
			writer.Put(_v10);
			writer.Put(_v12);
			writer.Put(_v13);
			writer.Put(_v15);
			writer.Put(_v16);
			writer.Put(_v18);
			writer.Put(_v19);
			writer.Put(_v20);
			writer.Put(_v21);
			writer.Put(_v23);
			writer.Put(_v25);
			writer.Put(_v26);
			writer.Put(_v27);
			writer.Put(_v29);
			writer.Put(_v30);
			writer.Put(_v31);
			writer.Put(_v32);
			writer.Put(_v33);
			writer.Put(_v35);
			writer.Put(_v36);
			writer.Put(_v37);
			writer.Put(_v38);
			writer.Put(_v39);
			writer.Put(_v40);
			writer.Put(_v43);
			writer.Put(_v44);
			writer.Put(_v45);
			writer.Put(_v46);
			writer.Put(_v47);
			writer.Put(_v48);
			writer.Put(_v50);
			writer.Put(_v51);
			writer.Put(_v52);
			writer.Put(_v53);
			writer.Put(_v55);
			writer.Put(_v56);
			writer.Put(_v57);
			writer.Put(_v58);
			writer.Put(_v59);
			writer.Put(_v60);
			writer.Put(_v62);
			writer.Put(_v63);
			writer.Put(_uv0);
			writer.Put(_uv1);
			writer.Put(_uv2);
			writer.Put(_uv4);
			writer.Put(_uv5);
			writer.Put(_uv6);
			writer.Put(_uv7);
			writer.Put(_uv8);
			writer.Put(_uv9);
			writer.Put(_uv10);
			writer.Put(_uv12);
			writer.Put(_uv13);
			writer.Put(_uv15);
			writer.Put(_uv16);
			writer.Put(_uv18);
			writer.Put(_uv19);
			writer.Put(_uv20);
			writer.Put(_uv21);
			writer.Put(_uv23);
			writer.Put(_uv25);
			writer.Put(_uv26);
			writer.Put(_uv27);
			writer.Put(_uv29);
			writer.Put(_uv30);
			writer.Put(_uv31);
			writer.Put(_uv32);
			writer.Put(_uv33);
			writer.Put(_uv35);
			writer.Put(_uv36);
			writer.Put(_uv37);
			writer.Put(_uv38);
			writer.Put(_uv39);
			writer.Put(_uv40);
			writer.Put(_uv43);
			writer.Put(_uv44);
			writer.Put(_uv45);
			writer.Put(_uv46);
			writer.Put(_uv47);
			writer.Put(_uv48);
			writer.Put(_uv50);
			writer.Put(_uv51);
			writer.Put(_uv52);
			writer.Put(_uv53);
			writer.Put(_uv55);
			writer.Put(_uv56);
			writer.Put(_uv57);
			writer.Put(_uv58);
			writer.Put(_uv59);
			writer.Put(_uv60);
			writer.Put(_uv62);
			writer.Put(_uv63);
		}
		public override void DeserializeSyncReliable(PacketReader reader) { }
		public override void DeserializeSyncUnreliable(PacketReader reader) { }
		public override void DeserializeEveryProperty(PacketReader reader) { }
	}
}
#pragma warning restore CS0649
