/*
 * Generated File : NetworkObjectType.cs
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

namespace CTS.Instance.SyncObjects
{
	public enum NetworkObjectType
	{
		None = 0,
		TestInnerObject,
		TestFuntionObject,
		TestValue64,
		TestValue16,
		TestValue8,
		TestNetworkObject,
		TestTypeSync,
	}
}
